import Foundation
import FerretParsers

/// Loads capture fixtures and the Wireshark reference values generated by
/// scripts/generate-fixture-expectations.sh.
enum Fixtures {
    static func url(_ name: String) throws -> URL {
        guard let url = Bundle.module.url(forResource: name, withExtension: nil, subdirectory: "Fixtures") else {
            throw FixtureError.missing(name)
        }
        return url
    }

    static func bytes(_ name: String) throws -> [UInt8] {
        Array(try Data(contentsOf: url(name)))
    }

    static func records(_ name: String) throws -> [CaptureRecord] {
        try CaptureFileReader.read(bytes(name))
    }

    /// One dictionary per frame, keyed by Wireshark field name.
    static func expectations(_ name: String) throws -> [[String: String]] {
        let text = try String(contentsOf: url("\(name).fields.tsv"), encoding: .utf8)
        var lines = text.split(separator: "\n", omittingEmptySubsequences: false).map(String.init)
        if lines.last == "" { lines.removeLast() }
        guard let header = lines.first?.components(separatedBy: "\t") else { return [] }
        return lines.dropFirst().map { line in
            let cells = line.components(separatedBy: "\t")
            var row: [String: String] = [:]
            for (i, key) in header.enumerated() {
                row[key] = i < cells.count ? cells[i] : ""
            }
            return row
        }
    }

    enum FixtureError: Error {
        case missing(String)
    }
}
